### ISSUE TITLE
Memo.h is not public header of Memo-iOS target

### ISSUE THREAD

**Issue by norio-nomura** [robrix/Memo#11]

**Comment by robrix** [comment]
This one is an Xcode fail. I actually set it as such two or three times and it kept resetting it, but it looked fine in the build phases so I let it go. Bah.

**Comment by robrix** [comment]
Given that there’s nothing in here usable from ObjC, is there any point to having the `.h` file at all?

**Comment by robrix** [comment]
Looks like you get an annoying warning about no umbrella header if it’s omitted.

**Comment by norio-nomura** [comment]
I have experienced some build errors with it on another project.
While writing above line, it fixed.
Thanks!

**Comment by robrix** [comment]
https://github.com/robrix/Memo/releases/tag/1.1.1 has been released now!

**Comment by norio-nomura** [comment]
👍
