### ISSUE TITLE
Workspace usage and manage dependence to Memo by Carthage

### ISSUE THREAD

**Issue by norio-nomura** [robrix/Memo#13]
Containing Box.xcodeproj into Memo.xcworkspace cause multiple time building Box.
Because `xcodebuild` will build targets of sub projects of project/workspace which specified by argument.
It seems whether main project target depend to target of sub project or not, framework target of sub project will be build.

On building [Stream](https://github.com/antitypical/Stream), 
```
% carthage bootstrap --verbose --no-skip-current
```
It starts with building Box by Carthage(log is after several tried to build)
```
*** Checking out Box at "18d05a56845837eea90a36854c67de2520983bf8"
*** Checking out Memo at "1.1"
*** Checking out Prelude at "180e9ae5e60ec47abd8f3e0fa68cafbbbd160abe"
*** Checking out Either at "1.2"
*** Building scheme "Box-iOS" in Box.xcodeproj
Build settings from command line:
    SDKROOT = iphonesimulator8.4

=== BUILD TARGET Box-iOS OF PROJECT Box WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/norio/Library/Developer/Xcode/DerivedData/Box-eqpibsraehojepfdwzyutsumelbi/Build/Intermediates/Box.build/all-product-headers.yaml

** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = iphoneos8.4

=== BUILD TARGET Box-iOS OF PROJECT Box WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/norio/Library/Developer/Xcode/DerivedData/Box-eqpibsraehojepfdwzyutsumelbi/Build/Intermediates/Box.build/all-product-headers.yaml

** BUILD SUCCEEDED **
<<<snip building log of Box-Mac>>>
```
building Memo include building Box following:
```
*** Building scheme "Memo-iOS" in Memo.xcworkspace
Build settings from command line:
    SDKROOT = iphonesimulator8.4

=== BUILD TARGET Box-Mac OF PROJECT Box WITH CONFIGURATION Release ===

Check dependencies

=== BUILD TARGET Memo-iOS OF PROJECT Memo WITH CONFIGURATION Release ===

Check dependencies

** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = iphoneos8.4

=== BUILD TARGET Box-iOS OF PROJECT Box WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/norio/Library/Developer/Xcode/DerivedData/Memo-aylvjocmrrmcozcchjqpaxxgcuml/Build/Intermediates/Box.build/all-product-headers.yaml

=== BUILD TARGET Memo-iOS OF PROJECT Memo WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/norio/Library/Developer/Xcode/DerivedData/Memo-aylvjocmrrmcozcchjqpaxxgcuml/Build/Intermediates/Memo.build/all-product-headers.yaml

** BUILD SUCCEEDED **
<<<snip building log of Memo-Mac>>>
```
If no code signing error, building Prelude following <<<snip log of Prelude-iOS, Prelude-Mac>>>.
If no code signing error, building Either including Box following:
```
*** Building scheme "Either-iOS" in Either.xcworkspace
Build settings from command line:
    SDKROOT = iphonesimulator8.4

=== BUILD TARGET Box-Mac OF PROJECT Box WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/norio/Library/Developer/Xcode/DerivedData/Either-feupdmvosjeqbqdzwbvdgoexgfzb/Build/Intermediates/Box.build/all-product-headers.yaml

=== BUILD TARGET Prelude-Mac OF PROJECT Prelude WITH CONFIGURATION Release ===
Check dependencies

Write auxiliary files
write-file /Users/norio/Library/Developer/Xcode/DerivedData/Either-feupdmvosjeqbqdzwbvdgoexgfzb/Build/Intermediates/Prelude.build/all-product-headers.yaml

=== BUILD TARGET Either-iOS OF PROJECT Either WITH CONFIGURATION Release ===

Check dependencies

Write auxiliary files
write-file /Users/norio/Library/Developer/Xcode/DerivedData/Either-feupdmvosjeqbqdzwbvdgoexgfzb/Build/Intermediates/Either.build/all-product-headers.yaml

** BUILD SUCCEEDED **

Build settings from command line:
    SDKROOT = iphoneos8.4

=== BUILD TARGET Prelude-Mac OF PROJECT Prelude WITH CONFIGURATION Release ===

Check dependencies
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.4'

=== BUILD TARGET Box-iOS OF PROJECT Box WITH CONFIGURATION Release ===
Check dependencies

Write auxiliary files
write-file /Users/norio/Library/Developer/Xcode/DerivedData/Either-feupdmvosjeqbqdzwbvdgoexgfzb/Build/Intermediates/Box.build/all-product-headers.yaml

A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```
On above, Building Prelude-Mac is failed for building Prelude-iOS with codesign error.

DerivedData contains multiple builded Box
![screenshot 2015-05-09 21 28 44](https://cloud.githubusercontent.com/assets/33430/7550163/6ee15612-f692-11e4-8477-538693b1bd21.png)

Maybe building Mac for iOS schema target is bug of `xcodebuild`, but building targets of sub project/workspace without dependency will be intentional behavior of `xcodebuild`.

Should we avoid containing subproject of dependent framework to framework project/workspace for using carthage as dependency manager?

**Comment by robrix** [comment]
Thanks for looking into this!

Building dependencies for the wrong platform is _definitely_ an `xcodebuild` bug, but we can probably improve things at least a little for `Memo` by adding a `Cartfile`, by adding binary releases, and by restricting the Mac framework to x86_64 a la @jspahrsummers’ [change to `Result`](https://github.com/antitypical/Result/pull/40).

**Comment by norio-nomura** [comment]
As far as I know, building dependencies for the wrong platform is only happen on building inferred dependencies by `xcodebuild` from sub projects in workspace/project.

e.g. Building [Stream(sub projects are removed from workspace)](https://github.com/norio-nomura/Stream/tree/dependencies) using [Memo(sub projects are removed from workspace)](https://github.com/norio-nomura/Memo/tree/dependencies), [Either(sub projects are removed from workspace)](https://github.com/norio-nomura/Either/tree/dependencies), [Box(VALID_ARCHS removed)](https://github.com/norio-nomura/Box/tree/dependencies) does not fail on my environment.

**Comment by robrix** [comment]
Yes, that’s correct. I’ve filed a radar, but Apple doesn’t fix bugs just cos I ask them nicely :smile:

**Comment by norio-nomura** [comment]
Oh, you already know.
Thank you for response my newbie issue. :pray: 
I wonder this is well known by carthage users.

I think carthage would have an option to select xcodeproj instead of xcworkspace for avoid building inferred targets by sub projects.

**Comment by robrix** [comment]
Well, feel free to file an issue against Carthage, but I think this is just the same old story: `xcodebuild` is buggy and there’s not much we can do about it :confused:

In the meantime, I’ve got all the relevant repos tagged with versions that build Mac for x86_64 only, and I’m not sure what else I can do. I’m therefore going to close this out now.
